### ISSUE TITLE
アプリケーションIDを.textlintrcに設定できるようにしてほしい

### ISSUE THREAD

**Issue by wate** [KeitaMoromizato/textlint-rule-ja-yahoo-kousei#6]
アプリケーションIDを環境変数としてを設定するのではなく、
.textlintrcに設定できるようにしてほしいです。

**Comment by KeitaMoromizato** [comment]
v1.0.2で対応完了。textlintrcにappIDを指定できるようにしました。

https://github.com/KeitaMoromizato/textlint-rule-ja-yahoo-kousei/pull/8

``` .textlintrc
{
  "rules": {
    "textlint-rule-ja-yahoo-kousei": {
      'appID': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    }
  }
}
```

対応遅くなってすいません..

**Comment by wate** [comment]
@KeitaMoromizato ありがとうございます！
